export const ADD_HOUSEHOLD = 'ADD_HOUSEHOLD'
export const ADD_RESIDENT = 'ADD_RESIDENT'
export const ADD_VEHICLE = 'ADD_VEHICLE'
export const SUBMIT_DATA = "SUBMIT_DATA"
export const POST_HOUSEHOLD_ERROR = 'POST_HOUSEHOLD_ERROR'
export const POST_HOUSEHOLD_RECEIVED = 'POST_HOUSEHOLD_RECEIVED'